# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 刘先玉           #网站标题
subtitle: 知易行难      #网站副标题
description:  Easier said than done      #详情
keywords: 随笔小站
author: liuxy0551       #作者
language: zh-CN         #语言
timezone: UTC           #时区

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
# url: http://liuxy0551.github.io # liuxy0551是我的账号，修改为自己的账号
url: https://liuxianyu.cn # liuxy0551是我的账号，修改为自己的账号
root: /
permalink: article/:urlname.html #:year/:month/:day/:title/
permalink_defaults:
    #alg: crc32  # 算法：crc16(default) and crc32
    #rep: hex    # 进制：dec(default) and hex

# Directory
source_dir: source
public_dir: public
tag_dir: tags             #标签
archive_dir: archives     #归档
category_dir: categories  #类别
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

#表示站内搜索
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: default
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: landscape
theme: next

live2d:
  enable: false
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: live2d-widget-model-koharu
  display:
    position: left
    width: 150
    height: 300
  mobile:
    show: false
  react:
    opacity: 0.7


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  #repository: https://github.com/liuxy0551/liuxy0551.github.io #复制过来
  #branch: master
  repo:
    github: git@github.com:liuxy0551/liuxy0551.github.io.git,master
    # coding: https://git.dev.tencent.com/liuxianyu/liuxy0551.coding.me.git,master
    # gitee: git@gitee.com:liuxy0551/liuxy0551.git,master
    server: deploy@43.139.150.206:/mnt/projects/hexo-blog/blog.git,master

admin:
  username: liuxy0551
  password_hash: $2a$10$MTlknhXAW0OvGiXKMuYXnudRAxAWuEuM.sPykv2eMF/HMfEoaF4W6 #你想设置密码生成的bcrypt hash安全密钥
  secret: nowonder

sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml


# 3D 标签旋转
tagCloud:
  enable: false

# hexo-tag-cloud 滚动标签
tag_cloud:
  textFont: Trebuchet MS, Helvetica
  textColor: '#fc6423'
  textHeight: 17
  outlineColor: '#b3e5ef'
  maxSpeed: 0.07


# 鼠标选取文字自动提示版权信息
selectionCopyright:
  enable: true


# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
  - markdown-it-abbr
  - markdown-it-footnote
  - markdown-it-ins
  - markdown-it-sub
  - markdown-it-sup
  - markdown-it-emoji  ## add emoji
  anchors:
    level: 1
    collisionSuffix: 'v'
    # If `true`, creates an anchor tag with a permalink besides the heading.
    permalink: true
    permalinkClass: header-anchor
    # The symbol used to make the permalink
    permalinkSymbol: ¶
