<script src="{{ url_for(theme.js) }}/src/scrollspy.js?v={{ version }}"></script>
<script src="{{ url_for(theme.js) }}/src/post-details.js?v={{ version }}"></script>

<script type="text/javascript" src="{{ url_for(theme.js) }}/src/photoswipe.min.js?v={{ theme.version }}"></script>
<script type="text/javascript" src="{{ url_for(theme.js) }}/src/photoswipe-ui-default.min.js?v={{ theme.version }}"></script>

<script defer src="https://umami.liuxianyu.cn/script.js" data-website-id="6b203b66-330d-4f68-b3ff-70282b97bceb"></script>
<script>window.console.log(`%c${new Date().toLocaleString()}`, 'font-family: Cabin, Helvetica, Arial, sans-serif;text-align: left;font-size:24px;color:#B21212;');</script>